# Generated by Django 3.2.16 on 2024-12-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=0, max_length=256, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
