# Generated by Django 3.2.16 on 2024-12-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': 'публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
